[ST07.1.2 - API] Post-login-test
STC-TEAM-PROJECT/robot-api-stc pull request #15
Opened 2022-06-01 20:10 UTC by RafaelFelice

**1. Task Description:**

Successfully login

**2. Testing Procedures:**

- `make run-test` 

**3. Comments:**

Creating Successfully login to use the token

**4. Checklist review:**

- [x] The branch name follows the feature-title pattern
- [x] PR name follows the pattern [TASK] title-of-feature
- [x] The PR is signed by someone
- [x] PR has the correct label
- [x] Is the build green?
- [x] Can the branch be deleted?

2022-06-01 20:53 UTC, uLucasFraga requested changes
podemos melhorar a utilização dos dados.

Deixar eles inputados na KW é má prática.

2022-06-04 12:40 UTC, LucasFelice approved these changes

2022-06-04 21:01 UTC, uLucasFraga approved these changes

2022-06-04 21:01 UTC, uLucasFraga commented on serverest/tests/integration-tests/TestLogin.robot
> +    Login                               invalido@qa.com   teste
In english! hahaha

`invalid@qa.com` and `test`.

2022-06-04 21:01 UTC, uLucasFraga commented on serverest/tests/integration-tests/TestLogin.robot
> +    Login                               fulano@qa.com   teste
In english! hahaha

`test`.

2022-06-05 15:08 UTC, merged