[ST07.1.6 - API] - Criar arquivo commons
STC-TEAM-PROJECT/robot-api-stc pull request #20
Opened 2022-06-08 12:28 UTC by RafaelFelice

**1. Task Description:**

Create file commons

**2. Testing Procedures:**

it's not possible

**3. Comments:**

Create file commons

**4. Checklist review:**

- [x] The branch name follows the feature-title pattern
- [x] PR name follows the pattern [TASK] title-of-feature
- [x] The PR is signed by someone
- [x] PR has the correct label
- [x] Is the build green?
- [x] Can the branch be deleted?

2022-06-08 23:08 UTC, uLucasFraga requested changes
@RafaelFelice you need to make the necessary fixes.
This PR doesn't make sense for me.

2022-06-08 23:08 UTC, uLucasFraga commented on serverest/tests/commons/Commons.robot
> +    ...                                 password=${password}3
What's that number "3"?

2022-06-08 23:08 UTC, uLucasFraga commented on serverest/tests/commons/Commons.robot
> +Create Users
@RafaelFelice this KW doesn't "create" anything.
I didn't understand the usage.

Could you explain to me, please? thanks.

2022-06-08 23:08 UTC, uLucasFraga commented on serverest/tests/commons/Commons.robot
> +    Create Users                        Phao  phao@qa.com  123  True
I don't understand what you tried to do here, sorry.

2022-06-08 23:08 UTC, uLucasFraga commented on serverest/tests/commons/Commons.robot
> +    Login                               phao@qa.com  123
@RafaelFelice I said we can't set a parameter on this KW, remember?

For example: phao

2022-06-15 00:18 UTC, uLucasFraga approved these changes

2022-06-15 00:18 UTC, LucasFelice approved these changes

2022-06-15 00:18 UTC, merged