Test schema carrinho
STC-TEAM-PROJECT/robot-api-stc pull request #7
Opened 2022-05-09 12:27 UTC by LucasFelice

**1. Task Description:**

- describe the task if necessary

**2. Testing Procedures:**

- `make run` - choose the required spec

**3. Comments:**

- write a comment if further understanding is needed

**4. Checklist review:**

- [ ] The branch name follows the feature-title pattern
- [ ] PR name follows the pattern [TASK] title-of-feature
- [ ] The PR is signed by someone
- [ ] PR has the correct label
- [ ] Is the build green?
- [ ] Can the branch be deleted?

2022-05-09 12:55 UTC, uLucasFraga commented
você não escreveu nada na descrição do PR, seria isso mesmo? @LucasFelice

2022-05-09 12:56 UTC, uLucasFraga requested changes
favor colocar todas as informações necessárias para abertura de pr.

2022-05-13 00:25 UTC, LucasFelice reviewed
Finalizado.

2022-05-13 00:25 UTC, fellipeconforto94 approved these changes
Reviewed

2022-05-13 00:26 UTC, uLucasFraga approved these changes
LGTM!

2022-05-13 00:26 UTC, uLucasFraga commented on serverest/tests/schema-tests/TestCarrinhosSchema.robot
> +Resource        ../integartion-tests/keywords/carrinhos/CarrinhoKW.robot
esse resource, como o projeto é pequeno, poderia ficar no `base.robot`

2022-05-13 00:26 UTC, uLucasFraga commented on serverest/tests/schema-tests/TestCarrinhosSchema.robot
> +    [Tags]    @regression
está faltando a tag `@schema`

2022-05-13 00:26 UTC, RafaelFelice approved these changes

2022-05-13 00:26 UTC, RafaelFelice commented on serverest/tests/schema-tests/TestCarrinhosSchema.robot
> +    [Tags]    @regression
Faltando tag @schema

2022-05-13 00:27 UTC, merged